// <auto-generated />
using System;
using EmployeeModule.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeModule.Migrations.VacancyDetail
{
    [DbContext(typeof(VacancyDetailContext))]
    partial class VacancyDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeModule.Context.VacancyDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Max_Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Min_Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Minimum_qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No_of_Vacancies")
                        .HasColumnType("int");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Published_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("no_of_applications")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
